onerror {resume}
quietly virtual function -install /MIPS_Processor_TB/DUV/IF_ID_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[31], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[30], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[29], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[28], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[27], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[26], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[25], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[24], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[23], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[22], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[21], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[20], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[19], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[18], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[17], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[16], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[15], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[14], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[13], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[12], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[11], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[10], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[9], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[8], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[7], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[6], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[5], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[4], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[3], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[2], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[1], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[0] }} ID_Instruction
quietly virtual function -install /MIPS_Processor_TB/DUV/IF_ID_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[63], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[62], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[61], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[60], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[59], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[58], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[57], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[56], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[55], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[54], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[53], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[52], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[51], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[50], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[49], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[48], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[47], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[46], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[45], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[44], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[43], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[42], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[41], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[40], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[39], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[38], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[37], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[36], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[35], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[34], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[33], /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/dataOut[32] }} ID_PC_4
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[31], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[30], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[29], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[28], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[27], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[26], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[25], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[24], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[23], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[22], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[21], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[20], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[19], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[18], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[17], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[16], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[15], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[14], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[13], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[12], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[11], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[10], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[9], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[8], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[7], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[6], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[5], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[4], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[3], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[2], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[1], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[0] }} EX_instruction
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[63], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[62], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[61], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[60], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[59], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[58], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[57], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[56], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[55], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[54], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[53], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[52], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[51], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[50], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[49], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[48], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[47], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[46], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[45], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[44], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[43], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[42], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[41], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[40], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[39], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[38], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[37], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[36], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[35], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[34], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[33], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[32] }} EX_PC_4
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { (concat_reverse)&{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[95], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[94], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[93], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[92], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[91], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[90], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[89], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[88], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[87], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[86], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[85], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[84], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[83], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[82], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[81], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[80], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[79], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[78], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[77], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[76], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[75], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[74], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[73], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[72], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[71], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[70], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[69], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[68], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[67], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[66], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[65], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[64] }} EX_IMMEDIATE_EXTEND
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[127], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[126], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[125], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[124], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[123], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[122], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[121], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[120], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[119], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[118], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[117], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[116], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[115], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[114], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[113], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[112], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[111], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[110], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[109], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[108], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[107], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[106], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[105], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[104], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[103], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[102], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[101], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[100], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[99], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[98], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[97], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[96] }} EX_Read_Data_3
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Read_Data_3  } EX_Read_Data_2
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[159], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[158], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[157], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[156], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[155], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[154], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[153], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[152], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[151], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[150], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[149], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[148], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[147], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[146], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[145], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[144], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[143], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[142], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[141], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[140], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[139], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[138], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[137], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[136], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[135], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[134], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[133], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[132], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[131], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[130], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[129], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[128] }} EX_Read_Data_1
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[160]  } EX_Jump
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[161]  } EX_Mem_Write
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[162]  } EX_Mem_To_Reg
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[164]  } EX_Reg_Write
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[165]  } EX_Alu_Src
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/PC { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[168], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[167], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[166] }} EX_ALU_Op
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[171]  } EX_Reg_Dst
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[170]  } EX_Branch_Ne
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[169]  } EX_Branch_Eq
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[168], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[167], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[166] }} EX_ALU_Op001
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[165]  } EX_ALU_Src
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[163]  } EX_Mem_Read
quietly virtual signal -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE {/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[160]  } EX_jump
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[159], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[158], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[157], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[156], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[155], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[154], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[153], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[152], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[151], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[150], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[149], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[148], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[147], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[146], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[145], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[144], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[143], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[142], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[141], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[140], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[139], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[138], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[137], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[136], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[135], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[134], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[133], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[132], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[131], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[130], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[129], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[128] }} EX_Read_Data_1001
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[127], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[126], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[125], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[124], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[123], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[122], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[121], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[120], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[119], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[118], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[117], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[116], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[115], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[114], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[113], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[112], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[111], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[110], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[109], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[108], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[107], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[106], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[105], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[104], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[103], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[102], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[101], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[100], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[99], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[98], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[97], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[96] }} EX_Read_Data_2001
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[95], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[94], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[93], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[92], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[91], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[90], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[89], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[88], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[87], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[86], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[85], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[84], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[83], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[82], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[81], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[80], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[79], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[78], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[77], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[76], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[75], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[74], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[73], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[72], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[71], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[70], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[69], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[68], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[67], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[66], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[65], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[64] }} EX_Immediate_Extend
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[63], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[62], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[61], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[60], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[59], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[58], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[57], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[56], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[55], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[54], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[53], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[52], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[51], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[50], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[49], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[48], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[47], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[46], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[45], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[44], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[43], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[42], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[41], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[40], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[39], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[38], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[37], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[36], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[35], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[34], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[33], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[32] }} EX_PC_4001
quietly virtual function -install /MIPS_Processor_TB/DUV/ID_EX_PIPELINE -env /MIPS_Processor_TB/DUV/ID_EX_PIPELINE { &{/MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[31], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[30], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[29], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[28], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[27], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[26], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[25], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[24], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[23], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[22], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[21], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[20], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[19], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[18], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[17], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[16], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[15], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[14], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[13], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[12], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[11], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[10], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[9], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[8], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[7], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[6], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[5], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[4], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[3], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[2], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[1], /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/dataOut[0] }} EX_Instruction
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[169]  } MEM_Jr
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[167]  } MEM_Branch_NE
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[166]  } MEM_Branch_Eq
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[165]  } MEM_Reg_Write
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[164]  } MEM_mem_read
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[163]  } MEM_Mem_To_Reg
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[162]  } MEM_Reg_Write001
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[162]  } MEM_mem_write
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[161]  } Mem_Jump
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[160], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[159], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[158], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[157], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[156], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[155], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[154], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[153], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[152], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[151], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[150], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[149], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[148], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[147], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[146], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[145], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[144], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[143], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[142], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[141], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[140], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[139], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[138], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[137], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[136], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[135], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[134], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[133], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[132], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[131], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[130], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[129] }} MEM_ALU_Result
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[128]  } MEM_Zero
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[127], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[126], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[125], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[124], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[123], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[122], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[121], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[120], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[119], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[118], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[117], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[116], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[115], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[114], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[113], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[112], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[111], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[110], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[109], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[108], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[107], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[106], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[105], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[104], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[103], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[102], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[101], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[100], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[99], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[98], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[97], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[96] }} MEM_Read_Data_2
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[95], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[94], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[93], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[92], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[91], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[90], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[89], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[88], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[87], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[86], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[85], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[84], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[83], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[82], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[81], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[80], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[79], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[78], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[77], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[76], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[75], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[74], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[73], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[72], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[71], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[70], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[69], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[68], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[67], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[66], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[65], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[64] }} MEM_PC_4
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[63], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[62], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[61], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[60], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[59], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[58], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[57], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[56], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[55], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[54], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[53], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[52], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[51], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[50], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[49], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[48], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[47], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[46], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[45], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[44], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[43], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[42], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[41], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[40], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[39], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[38], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[37], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[36], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[35], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[34], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[33], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[32] }} MEM_Instruction
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[31], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[30], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[29], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[28], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[27], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[26], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[25], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[24], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[23], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[22], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[21], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[20], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[19], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[18], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[17], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[16], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[15], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[14], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[13], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[12], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[11], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[10], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[9], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[8], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[7], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[6], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[5], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[4], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[3], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[2], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[1], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[0] }} MEM_PC_Branch
quietly virtual signal -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE {/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[168]  } MEM_Reg_Dst
quietly virtual signal -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE {/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[131]  } WB_Reg_Dst
quietly virtual signal -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE {/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[130]  } WB_Reg_Write
quietly virtual signal -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE {/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[129]  } WB_Mem_To_Reg
quietly virtual signal -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE {/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[128]  } WB_Jump
quietly virtual function -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[127], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[126], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[125], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[124], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[123], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[122], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[121], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[120], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[119], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[118], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[117], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[116], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[115], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[114], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[113], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[112], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[111], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[110], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[109], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[108], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[107], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[106], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[105], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[104], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[103], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[102], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[101], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[100], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[99], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[98], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[97], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[96] }} WB_ALU_Result
quietly virtual function -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[95], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[94], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[93], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[92], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[91], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[90], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[89], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[88], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[87], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[86], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[85], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[84], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[83], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[82], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[81], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[80], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[79], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[78], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[77], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[76], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[75], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[74], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[73], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[72], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[71], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[70], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[69], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[68], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[67], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[66], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[65], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[64] }} WB_Read_Data_Out
quietly virtual function -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[63], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[62], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[61], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[60], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[59], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[58], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[57], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[56], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[55], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[54], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[53], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[52], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[51], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[50], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[49], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[48], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[47], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[46], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[45], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[44], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[43], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[42], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[41], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[40], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[39], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[38], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[37], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[36], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[35], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[34], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[33], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[32] }} WB_PC_4
quietly virtual function -install /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE -env /MIPS_Processor_TB { &{/MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[31], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[30], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[29], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[28], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[27], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[26], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[25], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[24], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[23], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[22], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[21], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[20], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[19], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[18], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[17], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[16], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[15], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[14], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[13], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[12], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[11], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[10], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[9], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[8], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[7], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[6], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[5], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[4], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[3], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[2], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[1], /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/dataOut[0] }} WB_Instruction
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[169], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[168], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[167], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[166], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[165], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[164], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[163], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[162], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[161], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[160], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[159], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[158], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[157], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[156], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[155], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[154], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[153], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[152], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[151], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[150], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[149], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[148], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[147], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[146], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[145], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[144], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[143], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[142], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[141], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[140], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[139], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[138] }} MEM_Read_Data_1
quietly virtual function -install /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE -env /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE { &{/MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[201], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[200], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[199], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[198], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[197], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[196], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[195], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[194], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[193], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[192], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[191], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[190], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[189], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[188], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[187], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[186], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[185], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[184], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[183], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[182], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[181], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[180], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[179], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[178], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[177], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[176], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[175], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[174], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[173], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[172], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[171], /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/dataOut[170] }} MEM_Read_Data_1001
quietly WaveActivateNextPane {} 0
add wave -noupdate -label clk /MIPS_Processor_TB/clk_tb
add wave -noupdate -expand -group Program_Counter -radix hexadecimal /MIPS_Processor_TB/DUV/PC/pc_value_o
add wave -noupdate -expand -group Program_Counter -radix hexadecimal /MIPS_Processor_TB/DUV/PC/new_pc_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/reg_write_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/write_register_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/read_register_1_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/read_register_2_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/write_data_i
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/read_data_1_o
add wave -noupdate -group Register_File -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/read_data_2_o
add wave -noupdate -group PC_plus_4 -radix hexadecimal /MIPS_Processor_TB/DUV/PC_Puls_4/data_0_i
add wave -noupdate -group PC_plus_4 -radix hexadecimal /MIPS_Processor_TB/DUV/PC_Puls_4/data_1_i
add wave -noupdate -group PC_plus_4 -radix hexadecimal /MIPS_Processor_TB/DUV/PC_Puls_4/data_0_i
add wave -noupdate -group PC_plus_4 -radix hexadecimal /MIPS_Processor_TB/DUV/PC_Puls_4/data_1_i
add wave -noupdate -group MUX_PC4_BRANCH /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/mux_o
add wave -noupdate -group MUX_PC4_BRANCH -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/data_0_i
add wave -noupdate -group MUX_PC4_BRANCH -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/data_1_i
add wave -noupdate -group MUX_PC4_BRANCH /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/mux_o
add wave -noupdate -group MUX_PC4_BRANCH -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/data_0_i
add wave -noupdate -group MUX_PC4_BRANCH -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_PC_OR_BRANCH/data_1_i
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/data_0_i
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/data_1_i
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/mux_o
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/data_0_i
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/data_1_i
add wave -noupdate -group MUX_JUMP_PC -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_JUMP_OR_PC/mux_o
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/data_0_i
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/data_1_i
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/mux_o
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/data_0_i
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/data_1_i
add wave -noupdate -group MUX_PC_BR_J_JR -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_BranchPCJump_Or_Jr/mux_o
add wave -noupdate -group Registers -label s0 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/s0/data_o
add wave -noupdate -group Registers -label s1 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/s1/data_o
add wave -noupdate -group Registers -label s2 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/s2/data_o
add wave -noupdate -group Registers -label s3 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/s3/data_o
add wave -noupdate -group Registers -label t0 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/t0/data_o
add wave -noupdate -group Registers -label t1 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/t1/data_o
add wave -noupdate -group Registers -label t2 -radix hexadecimal /MIPS_Processor_TB/DUV/REGISTER_FILE_UNIT/t2/data_o
add wave -noupdate -expand -group ROM -radix hexadecimal /MIPS_Processor_TB/DUV/ROM/address_i
add wave -noupdate -expand -group ROM /MIPS_Processor_TB/DUV/ROM/real_address_r
add wave -noupdate -expand -group ROM -radix hexadecimal /MIPS_Processor_TB/DUV/ROM/instruction_o
add wave -noupdate -expand -group ALU -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/a_i
add wave -noupdate -expand -group ALU -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/b_i
add wave -noupdate -expand -group ALU -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/alu_data_o
add wave -noupdate -expand -group IF/ID -radix hexadecimal /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/ID_Instruction
add wave -noupdate -expand -group IF/ID -radix hexadecimal /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/ID_PC_4
add wave -noupdate -expand -group IF/ID -radix hexadecimal /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/ID_Instruction
add wave -noupdate -expand -group IF/ID -radix hexadecimal /MIPS_Processor_TB/DUV/IF_ID_PIPELINE/ID_PC_4
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Reg_Dst
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Branch_Ne
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Branch_Eq
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_ALU_Op001
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_ALU_Src
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Reg_Write
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_Read
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_To_Reg
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_Write
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_jump
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Read_Data_1001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Read_Data_2001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Immediate_Extend
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_PC_4001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Instruction
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Reg_Dst
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Branch_Ne
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Branch_Eq
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_ALU_Op001
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_ALU_Src
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Reg_Write
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_Read
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_To_Reg
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Mem_Write
add wave -noupdate -group ID/EX /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_jump
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Read_Data_1001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Read_Data_2001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Immediate_Extend
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_PC_4001
add wave -noupdate -group ID/EX -radix hexadecimal /MIPS_Processor_TB/DUV/ID_EX_PIPELINE/EX_Instruction
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Read_Data_1001
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Jr
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Reg_Dst
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Branch_NE
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Branch_Eq
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Reg_Write
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_mem_read
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Mem_To_Reg
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_mem_write
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/Mem_Jump
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_ALU_Result
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Zero
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Read_Data_2
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_PC_4
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Instruction
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_PC_Branch
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Read_Data_1001
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Jr
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Reg_Dst
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Branch_NE
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Branch_Eq
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Reg_Write
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_mem_read
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Mem_To_Reg
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_mem_write
add wave -noupdate -group EX/MEM /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/Mem_Jump
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_ALU_Result
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Zero
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Read_Data_2
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_PC_4
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_Instruction
add wave -noupdate -group EX/MEM -radix hexadecimal /MIPS_Processor_TB/DUV/EX_MEM_PIPELINE/MEM_PC_Branch
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Reg_Dst
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Reg_Write
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Mem_To_Reg
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Jump
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_ALU_Result
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Read_Data_Out
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_PC_4
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Instruction
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Reg_Dst
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Reg_Write
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Mem_To_Reg
add wave -noupdate -group MEM/WB /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Jump
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_ALU_Result
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Read_Data_Out
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_PC_4
add wave -noupdate -group MEM/WB -radix hexadecimal /MIPS_Processor_TB/DUV/MEM_WB_PIPELINE/WB_Instruction
add wave -noupdate -label ALU_RESULT -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/alu_data_o
add wave -noupdate -group Immediate_Extend -radix hexadecimal /MIPS_Processor_TB/DUV/SIGNED_EXTEND_FOR_CONSTANTS/sign_extend_o
add wave -noupdate -group Immediate_Extend -radix hexadecimal /MIPS_Processor_TB/DUV/SIGNED_EXTEND_FOR_CONSTANTS/sign_extend_o
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/selector_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/data_0_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/data_1_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/mux_o
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/selector_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/data_0_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/data_1_i
add wave -noupdate -expand -group Data2_Or_Immediate -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_READ_DATA_2_OR_IMMEDIATE/mux_o
add wave -noupdate -expand -group MUX_Forward_A_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_A_ALU_A/selector_i
add wave -noupdate -expand -group MUX_Forward_A_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_A_ALU_A/data_0_i
add wave -noupdate -expand -group MUX_Forward_A_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_A_ALU_A/data_1_i
add wave -noupdate -expand -group MUX_Forward_A_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_A_ALU_A/data_2_i
add wave -noupdate -expand -group MUX_Forward_A_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_A_ALU_A/mux_o
add wave -noupdate -expand -group MUX_Forward_B_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_B_ALU_B/selector_i
add wave -noupdate -expand -group MUX_Forward_B_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_B_ALU_B/data_0_i
add wave -noupdate -expand -group MUX_Forward_B_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_B_ALU_B/data_1_i
add wave -noupdate -expand -group MUX_Forward_B_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_B_ALU_B/data_2_i
add wave -noupdate -expand -group MUX_Forward_B_ALU_A -radix hexadecimal /MIPS_Processor_TB/DUV/MUX_Forward_B_ALU_B/mux_o
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/write_data_i
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/address_i
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/mem_write_i
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/mem_read_i
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/clk
add wave -noupdate -expand -group RAM -radix hexadecimal /MIPS_Processor_TB/DUV/RAM/data_o
add wave -noupdate -label clk /MIPS_Processor_TB/clk_tb
add wave -noupdate -label ALU_RESULT -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/alu_data_o
add wave -noupdate -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/a_i
add wave -noupdate -radix hexadecimal /MIPS_Processor_TB/DUV/ALU_UNIT/b_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {27 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 232
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {26 ps} {42 ps}
